name: routing_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.10
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  shared_preferences: ^2.3.4
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  firebase_crashlytics: ^4.3.0
  firebase_analytics: ^11.4.0
  firebase_messaging: ^15.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  path_provider: ^2.1.5
  path: ^1.9.0
  build_runner: ^2.4.13

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/databases/
    - assets/databases/data.db

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 400
          style: italic
